# fly.toml app configuration file generated for suddenlygiovanni-dev on 2024-03-03T02:43:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'suddenlygiovanni-dev'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = 5

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[services]]
internal_port = 3000
processes = ['app']
protocol = "tcp"

	[services.concurrency]
	hard_limit = 100
	soft_limit = 80
	type = "requests"

	[http_service]
	force_https = true
	auto_stop_machines = true
	auto_start_machines = true
	min_machines_running = 0

	[[services.ports]]
	handlers = [ "http" ]
	port = 80
	force_https = true

	[[services.ports]]
	handlers = [ "tls", "http" ]
	port = 443
