version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "monday"
    time: "04:00"
    timezone: Europe/Berlin
  target-branch: "dependencies"
  # Labels on pull requests for security and version updates
  labels:
    - "npm dependencies"
  open-pull-requests-limit: 10
