name: ðŸ’‰Setup the project
description: Perform standard setup and install dependencies using pnpm.
runs:
  using: composite
  steps:
    - name: ðŸ› ï¸ Install node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://npm.pkg.github.com'

    - id: get_pnpm_version
      shell: bash
      run: echo "version=$(jq -r '.devEngines.packageManager.version' package.json)" >> $GITHUB_OUTPUT

    - name: ðŸ—‚ï¸ Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: 'package.json'
        run_install: false
        version: ${{ steps.get_pnpm_version.outputs.version }}



    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: ðŸ§© Install dependencies
      shell: bash
      run: pnpm install --recursive --frozen-lockfile
