name: suddenlygiovannidev

services:
  web:
    env_file: .env
    build:
      platforms:
      - linux/amd64
      context: .
      dockerfile: packages/app/Dockerfile
      target: production
    ports:
      - "5173:5173"
    init: true
