packages:
  - packages/*
  - tools/*
catalog:
  react: ~19.1.0
  '@types/react': ^19.1.2
  react-dom: ~19.1.0
  '@types/react-dom': ^19.1.3
  '@total-typescript/ts-reset': 0.6.1
  vite: 6.3.5
  vitest: 3.1.3
  '@vitest/coverage-v8': 3.1.3
  '@vitest/ui': 3.1.3
  tailwindcss: 4.1.5
  '@tailwindcss/vite': 4.1.5
  babel-plugin-react-compiler: ^19.1.0-rc.1
  typescript: 5.8.3
  eslint: 9.25.1
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - esbuild
  - msw
autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: false
resolvePeersFromWorkspaceRoot: true
