packages:
  - packages/*
  - tools/*
catalog:
  react: ~19.0.0
  '@types/react': ^19.0.10
  react-dom: ~19.0.0
  '@types/react-dom': ^19.0.4
  '@total-typescript/ts-reset': 0.6.1
  vite: 6.1.1
  vitest: 3.0.7
  '@vitest/coverage-v8': 3.0.7
  '@vitest/ui': 3.0.7
  tailwindcss: 4.0.9
  '@tailwindcss/vite': 4.0.9
  babel-plugin-react-compiler: ^19.0.0-beta-21e868a-20250216
  typescript: ^5.8.1-rc
  eslint: 9.21.0
