packages:
  - packages/*
  - tools/*
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - esbuild
  - msw
autoInstallPeers: true
catalogMode: prefer
dedupePeerDependents: true
resolvePeersFromWorkspaceRoot: true
strictPeerDependencies: false
catalogs:
  lib:
    "@effect/platform": 0.87.0
    "@epic-web/client-hints": 1.3.5
    "@epic-web/invariant": 1.0.0
    "@octokit/core": 7.0.2
    "@octokit/plugin-rest-endpoint-methods": 16.0.0
    "@octokit/request-error": 7.0.0
    "@suddenly-giovanni/schema-resume": jsr:0.0.7
    effect: 3.16.9
    remix-utils: 8.3.1
    ts-brand: 0.2.0
  storybook:
    "@chromatic-com/storybook": 4.0.1
    "@storybook/addon-a11y": 9.1.0-alpha.2
    "@storybook/addon-docs": 9.1.0-alpha.2
    "@storybook/addon-links": 9.1.0-alpha.2
    "@storybook/addon-onboarding": 9.1.0-alpha.2
    "@storybook/addon-themes": 9.1.0-alpha.2
    "@storybook/react-vite": 9.1.0-alpha.2
    storybook: 9.1.0-alpha.2
  test:
    "@effect/vitest": 0.23.9
    "@vitest/coverage-v8": 3.2.4
    "@vitest/ui": 3.2.4
    msw: 2.7.6
    vitest: 3.2.4
  types: # Packages for type checking and definitions
    "@octokit/openapi-types": 25.1.0
    "@total-typescript/ts-reset": 0.6.1
    "@types/mdx": 2.0.13
    "@types/node": 22.15.32
    "@types/react": 19.1.8
    "@types/react-dom": 19.1.6
  lint: # Packages for linting/formatting
    "@biomejs/biome": 2.0.5
    "@eslint/js": 9.26.0
    "@typescript-eslint/eslint-plugin": 8.32.1
    "@typescript-eslint/parser": 8.32.1
    "@vitest/eslint-plugin": 1.1.44
    eslint-config-prettier: 10.1.5
    eslint-plugin-only-warn: 1.1.0
    eslint-plugin-react-hooks: 6.0.0-rc1
    eslint-plugin-react: 7.37.5
    eslint-plugin-storybook: 0.12.0
    eslint: 9.26.0
    globals: 16.0.0
    typescript-eslint: 8.32.1
  build: # Packages used for building the project
    "@babel/preset-typescript": 7.26.0
    "@codecov/vite-plugin": 1.9.1
    "@mdx-js/rollup": 3.1.0
    "@tailwindcss/vite": 4.1.10
    "@vitejs/plugin-react": 4.6.0
    babel-plugin-react-compiler: 19.1.0-rc.2
    react-router-devtools: 5.0.6
    vite-plugin-babel: 1.3.1
    vite-tsconfig-paths: 5.1.4
    vite: npm:rolldown-vite@latest
  frontend: # Packages for frontend development
    "@conform-to/react": 1.2.2
    "@radix-ui/react-accessible-icon": 1.1.7
    "@radix-ui/react-accordion": 1.2.11
    "@radix-ui/react-avatar": 1.1.10
    "@radix-ui/react-collapsible": 1.1.11
    "@radix-ui/react-dropdown-menu": 2.1.15
    "@radix-ui/react-icons": 1.3.2
    "@radix-ui/react-navigation-menu": 1.2.13
    "@radix-ui/react-separator": 1.1.7
    "@radix-ui/react-slot": 1.2.3
    "@radix-ui/react-switch": 1.2.5
    "@tailwindcss/typography": 0.5.16
    class-variance-authority: 0.7.1
    react-aria-components: 1.7.1
    react-dom: ~19.1.0
    react-router: 7.6.2
    react: ~19.1.0
    tailwind-merge: 3.3.1
    tailwind-variants: 1.0.0
    tailwindcss-animate: 1.0.7
    tailwindcss: 4.1.10
  backend: # Packages for the backend server.
    "@effect/platform-node": 0.88.2
    "@react-router/dev": 7.6.2
    "@react-router/node": 7.6.2
    "@std/yaml": jsr:1.0.6
    cookie: 1.0.2
    isbot: 5.1.28
  typescript:
    "@effect/language-service": 0.23.0
    "@tsconfig/node-ts": 23.6.1
    "@tsconfig/node24": 24.0.1
    "@tsconfig/strictest": 2.0.5
    "@tsconfig/vite-react": 6.3.6
    typescript: 5.8.3
