packages:
  - packages/*
  - tools/*
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - esbuild
  - msw
autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: false
resolvePeersFromWorkspaceRoot: true
catalogs:
  lib:
    "@effect/platform": 0.82.7
    "@epic-web/client-hints": 1.3.5
    "@epic-web/invariant": 1.0.0
    "@octokit/core": 7.0.1
    "@octokit/plugin-rest-endpoint-methods": 15.0.0
    "@octokit/request-error": 7.0.0
    effect: 3.15.4
    remix-utils: 8.3.1
    ts-brand: 0.2.0
  storybook:
    "@chromatic-com/storybook": 3.2.6
    "@storybook/addon-a11y": 8.6.14
    "@storybook/addon-essentials": 8.6.14
    "@storybook/addon-interactions": 8.6.14
    "@storybook/addon-links": 8.6.14
    "@storybook/addon-onboarding": 8.6.14
    "@storybook/addon-themes": 8.6.14
    "@storybook/blocks": 8.6.14
    "@storybook/react": 8.6.14
    "@storybook/react-vite": 8.6.14
    "@storybook/test": 8.6.14
    storybook: 8.6.14
  test: # Packages used for testing
    "@effect/vitest": 0.22.4
    "@vitest/coverage-v8": 3.1.4
    "@vitest/ui": 3.1.4
    msw: 2.7.6
    vitest: 3.1.4
  types: # Packages for type checking and definitions
    "@octokit/openapi-types": 25.0.0
    "@total-typescript/ts-reset": 0.6.1
    "@types/mdx": 2.0.13
    "@types/node": 22.15.19
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.3
  lint: # Packages for linting/formatting
    "@biomejs/biome": 2.0.0-beta.5
    "@eslint/js": 9.26.0
    "@typescript-eslint/eslint-plugin": 8.32.1
    "@typescript-eslint/parser": 8.32.1
    "@vitest/eslint-plugin": 1.1.44
    eslint-config-prettier: 10.1.5
    eslint-plugin-only-warn: 1.1.0
    eslint-plugin-react-hooks: 6.0.0-rc1
    eslint-plugin-react: 7.37.5
    eslint-plugin-storybook: 0.12.0
    eslint: 9.26.0
    globals: 16.0.0
    typescript-eslint: 8.32.1
  build: # Packages used for building the project
    "@babel/preset-typescript": 7.26.0
    "@codecov/vite-plugin": 1.9.0
    "@mdx-js/rollup": 3.1.0
    "@tailwindcss/vite": 4.1.7
    "@vitejs/plugin-react": 4.4.1
    babel-plugin-react-compiler: ^19.1.0-rc.1
    react-router-devtools: 5.0.5
    vite-plugin-babel: 1.3.1
    vite-tsconfig-paths: 5.1.4
    vite: 6.3.5
  frontend: # Packages for frontend development
    "@conform-to/react": 1.2.2
    "@radix-ui/react-accessible-icon": 1.1.6
    "@radix-ui/react-accordion": 1.2.10
    "@radix-ui/react-avatar": 1.1.9
    "@radix-ui/react-collapsible": 1.1.10
    "@radix-ui/react-dropdown-menu": 2.1.14
    "@radix-ui/react-icons": 1.3.2
    "@radix-ui/react-navigation-menu": 1.2.12
    "@radix-ui/react-separator": 1.1.6
    "@radix-ui/react-slot": 1.2.2
    "@radix-ui/react-switch": 1.2.4
    "@tailwindcss/typography": 0.5.16
    class-variance-authority: 0.7.1
    react-aria-components: 1.7.1
    react-dom: ~19.1.0
    react-router: 7.6.0
    react: ~19.1.0
    tailwind-merge: 3.3.0
    tailwind-variants: 1.0.0
    tailwindcss-animate: 1.0.7
    tailwindcss: 4.1.7
  backend: # Packages for the backend server.
    "@effect/platform-node": 0.81.4
    "@react-router/dev": 7.6.0
    "@react-router/node": 7.6.0
    cookie: 1.0.2
    isbot: 5.1.27
  typescript:
    "@effect/language-service": 0.16.7
    "@tsconfig/node-ts": 23.6.1
    "@tsconfig/node24": 24.0.1
    "@tsconfig/strictest": 2.0.5
    "@tsconfig/vite-react": 3.4.0
    typescript: 5.8.3
