packages:
  - packages/*
  - tools/*
catalog:
  react: ~19.0.0
  '@types/react': ^19.0.10
  react-dom: ~19.0.0
  '@types/react-dom': ^19.0.4
  '@total-typescript/ts-reset': 0.6.1
  vite: 6.2.0
  vitest: 3.0.7
  '@vitest/coverage-v8': 3.0.7
  '@vitest/ui': 3.0.7
  tailwindcss: 4.0.11
  '@tailwindcss/vite': 4.0.11
  babel-plugin-react-compiler: ^19.0.0-beta-21e868a-20250216
  typescript: 5.8.2
  eslint: 9.21.0
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - esbuild
  - msw
