packages:
  - "packages/*"
  - "tools/*"
catalog:
  react: ~19.0.0
  '@types/react': ^19.0.10
  react-dom: ~19.0.0
  '@types/react-dom': ^19.0.4
  '@total-typescript/ts-reset': 0.6.1
  vite: 6.1.1
  vitest: 3.0.6
  '@vitest/coverage-v8': 3.0.6
  '@vitest/ui': 3.0.6
