packages:
  - packages/*
  - tools/*
catalog:
  react: ~19.0.0
  '@types/react': ^19.0.10
  react-dom: ~19.0.0
  '@types/react-dom': ^19.0.4
  '@total-typescript/ts-reset': 0.6.1
  vite: 6.2.6
  vitest: 3.0.8
  '@vitest/coverage-v8': 3.0.8
  '@vitest/ui': 3.0.8
  tailwindcss: 4.1.4
  '@tailwindcss/vite': 4.1.4
  babel-plugin-react-compiler: ^19.0.0-beta-21e868a-20250216
  typescript: 5.8.3
  eslint: 9.22.0
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - esbuild
  - msw
autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: false
resolvePeersFromWorkspaceRoot: true
