#! /usr/bin/env bash

log_message="🏗️ Cleaning up node_modules directory..."

echo "$log_message"

# List of directories and files to remove
directories_and_files_to_remove=("dist" "out" "pruned" "build" "storybook-static" "coverage"
"tsconfig" ".tsbuildinfo" ".turbo" "node_modules" ".pnpm")

for item in "${directories_and_files_to_remove[@]}"
do
  if [ -d "$item" ]
  then
    rm -rf "$item"
    echo "✅ Removed directory '$item'"
  elif [ -f "$item" ]
  then
    rm "$item"
    echo "✅ Removed file '$item'"
  else
    echo "🔍'$item' does not exist; ✅ moving on..."
  fi
done

if [[ $? -eq 0 ]];
then echo "✅ Cleanup successful."
  else echo "❌ Cleanup failed."
fi
