#! /usr/bin/env bash

log_message="🏗️ Cleaning up node_modules directory..."

echo "$log_message"

# List of directories and files to remove
items_to_clean=("node_modules" ".pnpm" ".turbo" "dist" "build" "storybook-static" "tsconfig.tsbuildinfo")

for item in "${items_to_clean[@]}"
do
  if [ -d "$item" ]
  then
    rm -rf "$item"
    echo "✅ Removed directory '$item'"
  elif [ -f "$item" ]
  then
    rm "$item"
    echo "✅ Removed file '$item'"
  else
    echo "🔍'$item' does not exist; ✅ moving on..."
  fi
done

if [[ $? -eq 0 ]];
then echo "✅ Cleanup successful."
  else echo "❌ Cleanup failed."
fi
