#! /usr/bin/env bash



# Function to display help message
function display_help {
  echo "Usage: $0 [path]"
  echo
  echo "Format the specified directory or the current directory if no path is provided."
  echo
  echo "Options:"
  echo "  --help    Display this help message and exit."
}

# Check if --help is provided as an argument
if [[ $1 == "--help" ]]; then
  display_help
  exit 0
fi


# If a path is provided as an argument, use it. Otherwise, default to current directory.
path=${1:-.}

echo "🏗️ Formatting directory: '$path'"

pnpm exec prettier \
  --write \
  --ignore-path .prettierignore \
  --config .prettierrc.js \
  "$path/**/*.{ts,tsx,js,jsx,json,cjs,mjs}" \


if [[ $? -eq 0 ]];
then echo "✅ Formatting successful."
  else echo "❌ Formatting failed."
fi
