name: "Chromatic"
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/ui/**"
jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧩 Install dependencies
        uses: ./.github/actions/setup
        with:
          github_packages_token: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/ui
          skip: "@(renovate/**|dependabot/**)"
