name: 🚀 Deploy Preview

on:
  # Run this workflow on every PR event. Existing review apps will be updated when the PR is updated.
  pull_request:
    types: [ opened, reopened, synchronize, closed ]
# Allow only one preview deployment per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_APP_REVIEW }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: ams
  FLY_ORG: personal

jobs:
  deploy_preview:
    name: Build and Deploy Preview to Fly.io
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    environment:
      name: fly-preview-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for flyctl release naming

      - name: Generate Preview App Name
        id: app_name
        run: echo "app=suddenlygiovanni-dev-${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN has permissions for GHCR in the same repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and Push Docker Image for Preview
        id: docker_build_push
        uses: docker/build-push-action@v5
        if: ${{ github.event.action != 'closed' }}
        with:
          context: .
          file: ./packages/app/Dockerfile
          push: true # Push the image to the registry
          tags: ghcr.io/${{ github.repository }}/preview:pr-${{ github.event.number }}-${{ github.sha }}
          # Cache configuration (using registry)
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/cache:latest
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/cache:latest,mode=max

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.5.0
        with:
          config: ./packages/app/fly.review.yaml
          name: ${{ steps.app_name.outputs.app }}
          secrets: GITHUB_TOKEN=${{ secrets.OCTOKIT_RESUME_TOKEN }}
          image: ghcr.io/${{ github.repository }}/preview:pr-${{ github.event.number }}-${{ github.sha }}

      - name: 🗑 Delete deployment environment
        uses: strumwolf/delete-deployment-environment@v3
        if: ${{ github.event.action == 'closed' }}
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: suddenlygiovanni-dev-${{ github.event.number }}
