name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            monorepo
            ci
            packages/app
            packages/ui
            packages/open-graph-protocol
            tools/eslint
            tools/tailwind
            tools/typescript
          requireScope: true
          ignoreLabels: |
            dependencies
          wip: true
