name: 🔗Pull Request Checks Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  checks:
    name: 🫸 Pull Request Checks
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 🧩 Install dependencies
        uses: ./.github/actions/setup

      - name: 💅 Format code
        shell: sh
        run: |
          pnpm --shell-mode --reporter-hide-prefix exec \
          biome ci \
          --max-diagnostics=none \
          --formatter-enabled=true \
          --linter-enabled=false \
          --assist-enabled=true \
          --reporter=github

      - name: 🚨 Lint code
        shell: sh
        run: |
          pnpm --shell-mode --reporter-hide-prefix exec \
          biome ci \
          --max-diagnostics=none \
          --formatter-enabled=false \
          --linter-enabled=true \
          --assist-enabled=true \
          --reporter=github

      - name: 🔍 Typecheck code
        continue-on-error: true
        run: pnpm typecheck

      - name: 🧪 Run unit tests
        run: pnpm exec vitest run --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: suddenlyGiovanni/suddenlygiovanni.dev
          working-directory: packages/app
          directory: coverage
          fail_ci_if_error: false

      - name: 🏗️ Build project
        run: pnpm build
